services:
  postgres-kc:
    container_name: postgresql-kc
    image: 'postgres:17'
    hostname: 'pgkc'
    environment:
      - 'POSTGRES_DB=keycloak'
      - 'POSTGRES_PASSWORD=keycloak'
      - 'POSTGRES_USER=keycloak'
      - 'ADVERTISED_HOST=host.docker.internal'
      - 'ADVERTISED_PORT=25432'
    ports:
      - '25432:5432'
    expose:
      - '5432'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - keycloak-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U keycloak -p 5432" ]
      interval: 5s
      timeout: 5s
      retries: 5

  keycloak:
    image: cpomorska/kceventlistener
    container_name: kceventlistener
    environment:
      - 'KC_HEALTH_ENABLED=true'
      - 'KC_METRICS_ENABLED=true'
      - 'KC_HOSTNAME=host.docker.internal'
      - 'KC_HEALTH_ENABLED=true'
      - 'KC_METRICS_ENABLED=true'
      - 'KC_DB=postgres'
      - 'KC_DB_URL=jdbc:postgresql://postgresql-kc/keycloak'
      - 'KC_DB_USERNAME=keycloak'
      - 'KC_DB_PASSWORD=keycloak'
      - 'KEYCLOAK_ADMIN=admin'
      - 'KEYCLOAK_ADMIN_PASSWORD=admin'
    ports:
      - "8180:8080"
      - "8443:8443"
    depends_on:
        postgres-kc:
          condition: service_healthy
    networks:
      - keycloak-net

networks:
  keycloak-net:
    name: keycloak-net
    driver: bridge