name: Java CI with Maven

on:
  push:
    branches: [ "develop","main" ]
  pull_request:
    branches: [ "develop","main" ]
  merge_group:
    branches: [ "develop","main" ]

permissions:
  contents: read

env:
  JAVA_OPTS: -Xmx2g

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            java: 17
          - os: ubuntu-latest
            java: 21
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
      - name: Build with Maven
        run: mvn -B verify -Dmaven.test.skip=true --file pom.xml
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@49866fead7de0b0083b89f5f653f9620548ccddf
